### ISSUE TITLE
Astro ria and astro warna error di android tv,

### ISSUE THREAD

**Issue by Lee-Seven7** [KonSparrow92/sgtv#9]
Setiap kali ingin menonton channel ini akan tendang semula ke main menu, notification yg kluar java error 
![Screenshot_20240817_224303_studio scillarium ottnavigator](https://github.com/user-attachments/assets/17e569fb-abc0-484b-ad2d-b28fb1bd108b)

**Comment by KonSparrow92** [comment]
As all the channels are given free from this site, some channels may not be updated regularly. This is a pet project that I created in my free time.

It is recommended that you purchase your own channels from your local provider for a smoother and stable experience.
